services:
  postgresdb:
    container_name: "postgresdb"
    image: postgres
    restart: unless-stopped
    env_file: 
      -  ./.env
      - ./.env.local
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - ~/dbdata:/var/lib/postgresql/data
  application:
    image: node:18-alpine
    working_dir: /home/node
    command: sh -c "yarn install --frozen-lockfile && yarn start"
    depends_on:
      - postgresdb
    restart: unless-stopped
    env_file:
      - ./.env
      - ./.env.local
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_USER=$POSTGRESDB_USER
      - DATABASE_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DATABASE_NAME=$POSTGRESDB_DATABASE
      - DATABASE_PORT=$POSTGRESDB_LOCAL_PORT
    links:
      - postgresdb
    volumes:
      - ".:/home/node"


volumes:
   db:
